// <auto-generated />
using System;
using KlinikaMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KlinikaMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KlinikaMVC.Models.Administrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("Administratorzy");
                });

            modelBuilder.Entity("KlinikaMVC.Models.GrupaWsparcia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TerapeutaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TerapeutaId");

                    b.ToTable("GrupyWsparcia");
                });

            modelBuilder.Entity("KlinikaMVC.Models.KrokZadania", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TrescKroku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZadanieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZadanieId");

                    b.ToTable("KrokiZadania");
                });

            modelBuilder.Entity("KlinikaMVC.Models.NotatkaZWizyty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WizytaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WizytaId")
                        .IsUnique();

                    b.ToTable("NotatkiZWizyt");
                });

            modelBuilder.Entity("KlinikaMVC.Models.OdpowiedzPacjenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KrokId")
                        .HasColumnType("int");

                    b.Property<int>("PodejscieId")
                        .HasColumnType("int");

                    b.Property<int>("WybranaOpcjaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KrokId");

                    b.HasIndex("PodejscieId");

                    b.HasIndex("WybranaOpcjaId");

                    b.ToTable("OdpowiedziPacjentow");
                });

            modelBuilder.Entity("KlinikaMVC.Models.OpcjaOdpowiedzi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KrokId")
                        .HasColumnType("int");

                    b.Property<string>("TrescOpcji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KrokId");

                    b.ToTable("OpcjeOdpowiedzi");
                });

            modelBuilder.Entity("KlinikaMVC.Models.Pacjent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Dlug")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("Pacjenci");
                });

            modelBuilder.Entity("KlinikaMVC.Models.PacjentGrupa", b =>
                {
                    b.Property<int>("PacjentId")
                        .HasColumnType("int");

                    b.Property<int>("GrupaId")
                        .HasColumnType("int");

                    b.HasKey("PacjentId", "GrupaId");

                    b.HasIndex("GrupaId");

                    b.ToTable("PacjenciGrupy");
                });

            modelBuilder.Entity("KlinikaMVC.Models.PodejscieDoZadania", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRozpoczecia")
                        .HasColumnType("datetime2");

                    b.Property<int>("UdostepnienieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UdostepnienieId");

                    b.ToTable("PodejsciaDoZadania");
                });

            modelBuilder.Entity("KlinikaMVC.Models.PrzypisanieUzaleznienia", b =>
                {
                    b.Property<int>("PacjentId")
                        .HasColumnType("int");

                    b.Property<int>("UzaleznienieId")
                        .HasColumnType("int");

                    b.Property<int>("TypUzaleznieniaId")
                        .HasColumnType("int");

                    b.HasKey("PacjentId", "UzaleznienieId");

                    b.HasIndex("TypUzaleznieniaId");

                    b.ToTable("PrzypisaniaUzaleznien");
                });

            modelBuilder.Entity("KlinikaMVC.Models.StatusWizyty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StatusyWizyt");
                });

            modelBuilder.Entity("KlinikaMVC.Models.Terapeuta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specjalizacja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("Terapeuci");
                });

            modelBuilder.Entity("KlinikaMVC.Models.TypDanych", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Rozszerzenie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypyDanych");
                });

            modelBuilder.Entity("KlinikaMVC.Models.TypUzaleznienia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypyUzaleznien");
                });

            modelBuilder.Entity("KlinikaMVC.Models.UdostepnienieZadania", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PacjentId")
                        .HasColumnType("int");

                    b.Property<int>("ZadanieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacjentId");

                    b.HasIndex("ZadanieId");

                    b.ToTable("UdostepnieniaZadan");
                });

            modelBuilder.Entity("KlinikaMVC.Models.Wiadomosc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataWyslania")
                        .HasColumnType("datetime2");

                    b.Property<string>("NadawcaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NadawcaId");

                    b.ToTable("Wiadomosci");
                });

            modelBuilder.Entity("KlinikaMVC.Models.WiadomoscOdbiorca", b =>
                {
                    b.Property<int>("WiadomoscId")
                        .HasColumnType("int");

                    b.Property<string>("OdbiorcaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("CzyPrzeczytana")
                        .HasColumnType("bit");

                    b.HasKey("WiadomoscId", "OdbiorcaId");

                    b.HasIndex("OdbiorcaId");

                    b.ToTable("WiadomosciOdbiorcy");
                });

            modelBuilder.Entity("KlinikaMVC.Models.Wizyta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataWizyty")
                        .HasColumnType("datetime2");

                    b.Property<int>("PacjentId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TerapeutaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacjentId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TerapeutaId");

                    b.ToTable("Wizyty");
                });

            modelBuilder.Entity("KlinikaMVC.Models.Zadanie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TerapeutaId")
                        .HasColumnType("int");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TerapeutaId");

                    b.ToTable("Zadania");
                });

            modelBuilder.Entity("KlinikaMVC.Models.Zalacznik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Sciezka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypDanychId")
                        .HasColumnType("int");

                    b.Property<int>("WiadomoscId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypDanychId");

                    b.HasIndex("WiadomoscId");

                    b.ToTable("Zalaczniki");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KlinikaMVC.Models.Administrator", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("KlinikaMVC.Models.GrupaWsparcia", b =>
                {
                    b.HasOne("KlinikaMVC.Models.Terapeuta", "Terapeuta")
                        .WithMany("GrupyWsparcia")
                        .HasForeignKey("TerapeutaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Terapeuta");
                });

            modelBuilder.Entity("KlinikaMVC.Models.KrokZadania", b =>
                {
                    b.HasOne("KlinikaMVC.Models.Zadanie", "Zadanie")
                        .WithMany("Kroki")
                        .HasForeignKey("ZadanieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zadanie");
                });

            modelBuilder.Entity("KlinikaMVC.Models.NotatkaZWizyty", b =>
                {
                    b.HasOne("KlinikaMVC.Models.Wizyta", "Wizyta")
                        .WithOne("Notatka")
                        .HasForeignKey("KlinikaMVC.Models.NotatkaZWizyty", "WizytaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wizyta");
                });

            modelBuilder.Entity("KlinikaMVC.Models.OdpowiedzPacjenta", b =>
                {
                    b.HasOne("KlinikaMVC.Models.KrokZadania", "Krok")
                        .WithMany("OdpowiedziPacjentow")
                        .HasForeignKey("KrokId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KlinikaMVC.Models.PodejscieDoZadania", "Podejscie")
                        .WithMany("UdzieloneOdpowiedzi")
                        .HasForeignKey("PodejscieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KlinikaMVC.Models.OpcjaOdpowiedzi", "WybranaOpcja")
                        .WithMany("WybraneW")
                        .HasForeignKey("WybranaOpcjaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Krok");

                    b.Navigation("Podejscie");

                    b.Navigation("WybranaOpcja");
                });

            modelBuilder.Entity("KlinikaMVC.Models.OpcjaOdpowiedzi", b =>
                {
                    b.HasOne("KlinikaMVC.Models.KrokZadania", "Krok")
                        .WithMany("Opcje")
                        .HasForeignKey("KrokId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Krok");
                });

            modelBuilder.Entity("KlinikaMVC.Models.Pacjent", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("KlinikaMVC.Models.PacjentGrupa", b =>
                {
                    b.HasOne("KlinikaMVC.Models.GrupaWsparcia", "GrupaWsparcia")
                        .WithMany("PacjenciGrupy")
                        .HasForeignKey("GrupaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KlinikaMVC.Models.Pacjent", "Pacjent")
                        .WithMany("PacjenciGrupy")
                        .HasForeignKey("PacjentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrupaWsparcia");

                    b.Navigation("Pacjent");
                });

            modelBuilder.Entity("KlinikaMVC.Models.PodejscieDoZadania", b =>
                {
                    b.HasOne("KlinikaMVC.Models.UdostepnienieZadania", "Udostepnienie")
                        .WithMany("Podejscia")
                        .HasForeignKey("UdostepnienieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Udostepnienie");
                });

            modelBuilder.Entity("KlinikaMVC.Models.PrzypisanieUzaleznienia", b =>
                {
                    b.HasOne("KlinikaMVC.Models.Pacjent", "Pacjent")
                        .WithMany("PrzypisaniaUzaleznien")
                        .HasForeignKey("PacjentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KlinikaMVC.Models.TypUzaleznienia", "TypUzaleznienia")
                        .WithMany("PrzypisaniaUzaleznien")
                        .HasForeignKey("TypUzaleznieniaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacjent");

                    b.Navigation("TypUzaleznienia");
                });

            modelBuilder.Entity("KlinikaMVC.Models.Terapeuta", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("KlinikaMVC.Models.UdostepnienieZadania", b =>
                {
                    b.HasOne("KlinikaMVC.Models.Pacjent", "Pacjent")
                        .WithMany("UdostepnieniaZadan")
                        .HasForeignKey("PacjentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KlinikaMVC.Models.Zadanie", "Zadanie")
                        .WithMany("Udostepnienia")
                        .HasForeignKey("ZadanieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacjent");

                    b.Navigation("Zadanie");
                });

            modelBuilder.Entity("KlinikaMVC.Models.Wiadomosc", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Nadawca")
                        .WithMany()
                        .HasForeignKey("NadawcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nadawca");
                });

            modelBuilder.Entity("KlinikaMVC.Models.WiadomoscOdbiorca", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Odbiorca")
                        .WithMany()
                        .HasForeignKey("OdbiorcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KlinikaMVC.Models.Wiadomosc", "Wiadomosc")
                        .WithMany("Odbiorcy")
                        .HasForeignKey("WiadomoscId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Odbiorca");

                    b.Navigation("Wiadomosc");
                });

            modelBuilder.Entity("KlinikaMVC.Models.Wizyta", b =>
                {
                    b.HasOne("KlinikaMVC.Models.Pacjent", "Pacjent")
                        .WithMany("Wizyty")
                        .HasForeignKey("PacjentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KlinikaMVC.Models.StatusWizyty", "Status")
                        .WithMany("Wizyty")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KlinikaMVC.Models.Terapeuta", "Terapeuta")
                        .WithMany("Wizyty")
                        .HasForeignKey("TerapeutaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pacjent");

                    b.Navigation("Status");

                    b.Navigation("Terapeuta");
                });

            modelBuilder.Entity("KlinikaMVC.Models.Zadanie", b =>
                {
                    b.HasOne("KlinikaMVC.Models.Terapeuta", "Terapeuta")
                        .WithMany("Zadania")
                        .HasForeignKey("TerapeutaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Terapeuta");
                });

            modelBuilder.Entity("KlinikaMVC.Models.Zalacznik", b =>
                {
                    b.HasOne("KlinikaMVC.Models.TypDanych", "TypDanych")
                        .WithMany("Zalaczniki")
                        .HasForeignKey("TypDanychId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KlinikaMVC.Models.Wiadomosc", "Wiadomosc")
                        .WithMany("Zalaczniki")
                        .HasForeignKey("WiadomoscId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypDanych");

                    b.Navigation("Wiadomosc");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KlinikaMVC.Models.GrupaWsparcia", b =>
                {
                    b.Navigation("PacjenciGrupy");
                });

            modelBuilder.Entity("KlinikaMVC.Models.KrokZadania", b =>
                {
                    b.Navigation("OdpowiedziPacjentow");

                    b.Navigation("Opcje");
                });

            modelBuilder.Entity("KlinikaMVC.Models.OpcjaOdpowiedzi", b =>
                {
                    b.Navigation("WybraneW");
                });

            modelBuilder.Entity("KlinikaMVC.Models.Pacjent", b =>
                {
                    b.Navigation("PacjenciGrupy");

                    b.Navigation("PrzypisaniaUzaleznien");

                    b.Navigation("UdostepnieniaZadan");

                    b.Navigation("Wizyty");
                });

            modelBuilder.Entity("KlinikaMVC.Models.PodejscieDoZadania", b =>
                {
                    b.Navigation("UdzieloneOdpowiedzi");
                });

            modelBuilder.Entity("KlinikaMVC.Models.StatusWizyty", b =>
                {
                    b.Navigation("Wizyty");
                });

            modelBuilder.Entity("KlinikaMVC.Models.Terapeuta", b =>
                {
                    b.Navigation("GrupyWsparcia");

                    b.Navigation("Wizyty");

                    b.Navigation("Zadania");
                });

            modelBuilder.Entity("KlinikaMVC.Models.TypDanych", b =>
                {
                    b.Navigation("Zalaczniki");
                });

            modelBuilder.Entity("KlinikaMVC.Models.TypUzaleznienia", b =>
                {
                    b.Navigation("PrzypisaniaUzaleznien");
                });

            modelBuilder.Entity("KlinikaMVC.Models.UdostepnienieZadania", b =>
                {
                    b.Navigation("Podejscia");
                });

            modelBuilder.Entity("KlinikaMVC.Models.Wiadomosc", b =>
                {
                    b.Navigation("Odbiorcy");

                    b.Navigation("Zalaczniki");
                });

            modelBuilder.Entity("KlinikaMVC.Models.Wizyta", b =>
                {
                    b.Navigation("Notatka")
                        .IsRequired();
                });

            modelBuilder.Entity("KlinikaMVC.Models.Zadanie", b =>
                {
                    b.Navigation("Kroki");

                    b.Navigation("Udostepnienia");
                });
#pragma warning restore 612, 618
        }
    }
}
